manifest_version = 1

[[backend]]
name = "api.openweathermap.org"
host = "api.openweathermap.org"
port = 443

[[dictionary]]
name = "weather_auth"

[[dictionary.key]]
key = "key"
type = "string"
comment = "API token for openweathermap.org"
